# Generated by Django 4.1.4 on 2023-01-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESD_Project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clubname', models.CharField(max_length=120, verbose_name='Club Name')),
                ('clubrep', models.CharField(max_length=120, verbose_name='Representative')),
                ('password', models.CharField(max_length=120, verbose_name='Password')),
                ('address', models.CharField(max_length=200, verbose_name='Club Address')),
            ],
        ),
    ]
