# Generated by Django 4.1.4 on 2023-01-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESD_Project', '0002_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='balance',
            field=models.CharField(default=0, max_length=100, verbose_name='Balance'),
        ),
    ]
