# Generated by Django 4.1.4 on 2023-01-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESD_Project', '0003_club_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='address',
            field=models.TextField(max_length=200, verbose_name='Club Address'),
        ),
    ]
