# Generated by Django 4.1.4 on 2023-01-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESD_Project', '0005_alter_club_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='clubnumber',
            field=models.CharField(default=0, max_length=10, verbose_name='Club Number'),
        ),
        migrations.AddField(
            model_name='club',
            name='phonenumber',
            field=models.CharField(default=0, max_length=11, verbose_name='Phone Number'),
        ),
    ]
