# Generated by Django 4.1.4 on 2023-01-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESD_Project', '0008_alter_paymentmethod_cardnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='expireydate',
            field=models.CharField(max_length=5, verbose_name='Expire Date'),
        ),
    ]
