# Generated by Django 4.1.4 on 2023-01-04 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ESD_Project', '0009_alter_paymentmethod_expireydate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='expireydate',
            new_name='c_expireydate',
        ),
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='cardname',
            new_name='c_name',
        ),
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='cardnumber',
            new_name='c_number',
        ),
    ]
