# Generated by Django 4.1.4 on 2023-01-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESD_Project', '0010_rename_expireydate_paymentmethod_c_expireydate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filmname', models.CharField(max_length=120, verbose_name='Film Name')),
            ],
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='c_type',
            field=models.CharField(choices=[('1', '...'), ('2', 'Credit'), ('3', 'Debit')], default='1', max_length=11, verbose_name='Type'),
        ),
    ]
