# Generated by Django 4.1.4 on 2023-01-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESD_Project', '0011_film_paymentmethod_c_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='filmname',
        ),
        migrations.AddField(
            model_name='film',
            name='agerating',
            field=models.CharField(choices=[('G', 'G'), ('PG', 'PG'), ('PG-13', 'PG-13'), ('R', 'R'), ('18', '18')], default='G', max_length=8, verbose_name='Age Rating'),
        ),
        migrations.AddField(
            model_name='film',
            name='duration',
            field=models.CharField(default='1.00', max_length=4, verbose_name='Duration'),
        ),
        migrations.AddField(
            model_name='film',
            name='filmdescription',
            field=models.TextField(null=True, verbose_name='Film Description'),
        ),
        migrations.AddField(
            model_name='film',
            name='filmtitle',
            field=models.CharField(default='New Film', max_length=120, verbose_name='Film Title'),
        ),
    ]
