# Generated by Django 4.1.4 on 2023-01-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESD_Project', '0012_remove_film_filmname_film_agerating_film_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='showingday',
            field=models.CharField(choices=[('mon', 'MON'), ('tue', 'TUE'), ('wed', 'WED'), ('thu', 'THU'), ('fri', 'FRI'), ('sat', 'SAT'), ('sun', 'SUN')], default='mon', max_length=3, verbose_name='Day'),
        ),
    ]
